ifeq ($(CONFIG_OF),y)

dtb-$(CONFIG_SOC_IMX6Q) += \
	imx6q-c-sabresd.dtb \
	imx6dl-c-sabresd.dtb \
        imx6q-s3-sabresd.dtb \
        imx6dl-s3-sabresd.dtb
endif

always         := $(dtb-y)
clean-files    := *.dtb

